spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://mysql-container-name:3306/shop
    username: root
    password: 1234567@
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  data:
    redis:
      port: 6379
      host: redis-container
jwt:
  secret:
    key: 7Iqk7YyM66W07YOA7L2U65Sp7YG065+9U3ByaW5n6rCV7J2Y7Yqc7YSw7LWc7JuQ67mI7J6F64uI64ukLg==
